// Generates src/lib/components/theme.css from src/lib/themes/presets.js.
// Run with: pnpm run gen:theme  (also runs before build:lib)
import { writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";
import { themes } from "../src/lib/themes/presets.js";
import { generateThemeCss } from "../src/lib/themes/generator.js";
import { styleFonts } from "../src/lib/themes/fonts.js";

const __dirname = dirname(fileURLToPath(import.meta.url));
const outPath = join(__dirname, "..", "src", "lib", "components", "theme.css");

let out = `/* AUTO-GENERATED by scripts/gen-theme.js — DO NOT EDIT BY HAND.
 * Source: src/lib/themes/presets.js + generator.js + fonts.js
 * Regenerate with: pnpm run gen:theme
 */
@import "./theme-base.css";

`;

for (const [name, cfg] of Object.entries(themes)) {
  const { light, dark } = generateThemeCss(name, cfg);
  out += light + "\n\n";
  out += dark + "\n\n";
}

// Per-style default fonts (design guidelines). Apply by adding the class to a
// wrapper (or let initMultistyleUI apply it to <html>). --t-font cascades; an
// inline --t-font set by init({ font }) or a font selector overrides these.
out += `/* Per-style default fonts (design guidelines). */
/* Add .ms-font-<style> to a wrapper, or set --t-font inline to override. */
`;
for (const [style, font] of Object.entries(styleFonts)) {
  out += `.ms-font-${style} { --t-font: ${font}; }\n`;
}

writeFileSync(outPath, out);
console.log(`wrote ${outPath} (${out.length} bytes, ${Object.keys(themes).length} themes, ${Object.keys(styleFonts).length} style fonts)`);